version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.7
    container_name: debezium_zookeeper
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
    networks:
     - hoangnv_mongodb_connect

  kafka:
    image: debezium/kafka:1.7
    container_name: kafka
    ports:
     - 15243:15243
    networks:
     - hoangnv_mongodb_connect
    links:
     - zookeeper
    environment:
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:7395,PLAINTEXT_HOST://0.0.0.0:15243
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:7395,PLAINTEXT_HOST://192.168.50.17:15243
  mongodb:
    image: debezium/mongodb:1.7
    build: 
      context: mongodb
    container_name: mongodb
    ports:
     - 9876:27017
    networks:
     - hoangnv_mongodb_connect
    environment:
     - MONGODB_USER=edsolabs
     - MONGODB_PASSWORD=edso
     
  connect:
    image: debezium/connect:0.10
    container_name: debezium_connect
    ports:
     - 8084:8083
    networks:
     - hoangnv_mongodb_connect 
    links:
     - kafka
     - mongodb
    environment:
     - BOOTSTRAP_SERVERS=kafka:7395
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses

networks:
  hoangnv_mongodb_connect:
    external: true
    name: hoangnv